openapi: 3.0.0
info:
  title: "APILotacao"
  description: "APILotacao"
  version: "20250409220308"
servers:
  - url: http://localhost:8080/ProjetoPraticoJavaPostgreSQL/
paths:
  /lotacao:
    post:
      tags:
        - APILotacao  
      operationId: "APILotacao.lotacao__post"
      summary: "lotacao__post"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/lotacao__postInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/lotacao__postOutput"
        404:
          description: "Not found"

  /lotacao/{lot_id}:
    put:
      tags:
        - APILotacao  
      operationId: "APILotacao.lotacao__put"
      summary: "lotacao__put"
      parameters:
        - name: "lot_id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"

      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/lotacao__putInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/lotacao__putOutput"
        404:
          description: "Not found"


    delete:
      tags:
        - APILotacao  
      operationId: "APILotacao.lotacao__delete"
      summary: "lotacao__delete"
      parameters:
        - name: "lot_id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"

    get:
      tags:
        - APILotacao  
      operationId: "APILotacao.lotacao__get"
      summary: "lotacao__get"
      parameters:
        - name: "lot_id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/lotacao__getOutput"
        404:
          description: "Not found"

components:
  schemas:
    lotacao__postOutput:
      properties:
        RetornoSDTCRLotacao:
          description: "SDTCRLotacao"
          $ref: "#/components/schemas/SDTCRLotacao"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    lotacao__putOutput:
      properties:
        RetornoSDTCRLotacao:
          description: "SDTCRLotacao"
          $ref: "#/components/schemas/SDTCRLotacao"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"


    lotacao__getOutput:
      properties:
        SDTCRLotacao:
          description: "SDTCRLotacao"
          $ref: "#/components/schemas/SDTCRLotacao"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    lotacao__postInput:  
      properties:
        SDTCRLotacao:
          description: "SDTCRLotacao"
          $ref: "#/components/schemas/SDTCRLotacao"

    lotacao__putInput:  
      properties:
        SDTCRLotacao:
          description: "SDTCRLotacao"
          $ref: "#/components/schemas/SDTCRLotacao"


  
    SDTCRLotacao:
      properties:
        lot_id:
          description: "lot_id"
          type: "integer"
          format: "int64"
        pes_id:
          description: "pes_id"
          type: "integer"
          format: "int64"
        unid_id:
          description: "unid_id"
          type: "integer"
          format: "int64"
        lot_data_lotacao:
          description: "lot_data_lotacao"
          type: "string"
          format: "date"
        lot_data_remocao:
          description: "lot_data_remocao"
          type: "string"
          format: "date"
        lot_portaria:
          description: "lot_portaria"
          type: "string"
        pes_nome:
          description: "pes_nome"
          type: "string"
        pes_data_nascimento:
          description: "pes_data_nascimento"
          type: "string"
          format: "date"
        pes_sexo:
          description: "pes_sexo"
          type: "string"
        pes_mae:
          description: "pes_mae"
          type: "string"
        pes_pai:
          description: "pes_pai"
          type: "string"
        unid_nome:
          description: "unid_nome"
          type: "string"
        unid_sigla:
          description: "unid_sigla"
          type: "string"



    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"



 
