openapi: 3.0.0
info:
  title: "APIAuth"
  description: "APIAuth"
  version: "20250408181335"
servers:
  - url: http://localhost:8080/ProjetoPraticoJavaPostgreSQL/
paths:
  /auth:
    post:
      tags:
        - APIAuth  
      operationId: "APIAuth.auth"
      summary: "auth"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/authInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/authOutput"
        404:
          description: "Not found"

  /refresh:
    post:
      tags:
        - APIAuth  
      operationId: "APIAuth.refresh"
      summary: "refresh"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/refreshInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/refreshOutput"
        404:
          description: "Not found"

components:
  schemas:
    authOutput:
      properties:
        token:
          type: "string"
        refreshToken:
          type: "string"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    refreshOutput:
      properties:
        token:
          type: "string"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    authInput:  
      properties:
        username:
          type: "string"
        password:
          type: "string"

    refreshInput:  
      properties:
        refreshToken:
          type: "string"
  
    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"



 
