openapi: 3.0.0
info:
  title: "APIUnidade"
  description: "APIUnidade"
  version: "20250408181335"
servers:
  - url: http://localhost:8080/ProjetoPraticoJavaPostgreSQL/
paths:
  /unidade:
    post:
      tags:
        - APIUnidade  
      operationId: "APIUnidade.unidade__post"
      summary: "unidade__post"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/unidade__postInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/unidade__postOutput"
        404:
          description: "Not found"

  /unidade/{unid_id}:
    put:
      tags:
        - APIUnidade  
      operationId: "APIUnidade.unidade__put"
      summary: "unidade__put"
      parameters:
        - name: "unid_id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"

      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/unidade__putInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/unidade__putOutput"
        404:
          description: "Not found"


    delete:
      tags:
        - APIUnidade  
      operationId: "APIUnidade.unidade__delete"
      summary: "unidade__delete"
      parameters:
        - name: "unid_id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeneXus.Common.Messages_Message"  

        404:
          description: "Not found"

    get:
      tags:
        - APIUnidade  
      operationId: "APIUnidade.unidade__get"
      summary: "unidade__get"
      parameters:
        - name: "unid_id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/unidade__getOutput"
        404:
          description: "Not found"

components:
  schemas:
    unidade__postOutput:
      properties:
        RetornoSDTCRUnidade:
          description: "SDTCRUnidade"
          $ref: "#/components/schemas/SDTCRUnidade"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    unidade__putOutput:
      properties:
        RetornoSDTCRUnidade:
          description: "SDTCRUnidade"
          $ref: "#/components/schemas/SDTCRUnidade"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"


    unidade__getOutput:
      properties:
        SDTCRUnidade:
          description: "SDTCRUnidade"
          $ref: "#/components/schemas/SDTCRUnidade"
        Messages:
          description: "Messages"
          type: array
          items:
            $ref: "#/components/schemas/GeneXus.Common.Messages_Message"

    unidade__postInput:  
      properties:
        SDTCRUnidade:
          description: "SDTCRUnidade"
          $ref: "#/components/schemas/SDTCRUnidade"

    unidade__putInput:  
      properties:
        SDTCRUnidade:
          description: "SDTCRUnidade"
          $ref: "#/components/schemas/SDTCRUnidade"


  
    SDTCRUnidade:
      properties:
        unid_id:
          description: "unid_id"
          type: "integer"
          format: "int64"
        unid_nome:
          description: "unid_nome"
          type: "string"
        unid_sigla:
          description: "unid_sigla"
          type: "string"

        endereco:
          type: array
          items:
            description: enderecoItem
            $ref: "#/components/schemas/SDTCRUnidade.endereco_enderecoItem"


    SDTCRUnidade.endereco_enderecoItem:
      properties:
        end_id:
          description: "end_id"
          type: "integer"
          format: "int64"
        end_tipo_logradouro:
          description: "end_tipo_logradouro"
          type: "string"
        end_logradouro:
          description: "end_logradouro"
          type: "string"
        end_numero:
          description: "end_numero"
          type: "integer"
          format: "int64"
        end_bairro:
          description: "end_bairro"
          type: "string"
        cid_id:
          description: "cid_id"
          type: "integer"
          format: "int64"
        cid_nome:
          description: "cid_nome"
          type: "string"
        cid_uf:
          description: "cid_uf"
          type: "string"


      x-gx-level: "SDTCRUnidade"

    GeneXus.Common.Messages_Message:
      properties:
        Id:
          description: "Id"
          type: "string"
        Type:
          description: "Type"
          type: "integer"
          format: "int32"
        Description:
          description: "Description"
          type: "string"



 
